---
title: "fundamentus"
author: "Maxwel Coura Oliveira"
date: "4/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(rvest)
library(tidyverse)
library(lubridate)
```


```{r}
fundamentus <- read_html("https://www.fundamentus.com.br/resultado.php")
```



```{r}
fundamentus1 <- fundamentus %>% 
    html_node("table") %>% # selector = table
    html_table(fill = TRUE) # get a table
```


```{r}
fundamentus2 <- fundamentus1 %>% 
  janitor::clean_names() %>% 
  mutate(papel = as_factor(papel)) %>% 
  mutate_if(is.character,
            ~ str_replace_all(., "\\.", "")) %>% 
  mutate_if(is_character, ~ str_replace_all(., ",", "\\.")) %>% 
  mutate_at(c("div_yield", "mrg_liq", "roe", "cresc_rec_5a", "mrg_ebit", "roic"), 
            ~ str_remove(., "%")) %>% 
  rename(`div_yield_%` = div_yield,
         `mrg_liq_%` = mrg_liq,
         `roe_%` = roe,
         `cresc_rec_5a_%` = cresc_rec_5a,
         `roic_%` = roic,
         `mrg_ebit_%` = mrg_ebit) %>% 
  mutate_if(is_character, as.double)
```



```{r}
# ROE (Retorno sobre o patrimônio líquido)
# ROE = Lucro liquido / Patrimônio líquido
fundamentus2 %>%  
  arrange(desc(`roe_%`)) %>% 
  dplyr::select(papel, `roe_%`) %>% 
  filter(papel %in% c("ENBR3", "PETR4", "SULA11",
                      "CSMG3", "CMIG4", "ENAT3",
                      "MGLU3", "BBSE3", "BBAS3",
                      "SAPR4", "EQTL3", "CMIN3",
                      "VALE3", "BBDC4", "TAEE11",
                      "B3SA3", "ITSA4", "RANI3",
                      "MULT3"))
```


```{r}
# ROIC (Retorno sobre o capital investido)
# ROIC = EBIT (lucro operacional) / Capital investido (debendures, lucro anterior etc)
# EBIT = lucro - depreciação - amortização (+ juros + impostos)
fundamentus2 %>% 
  arrange(desc(`roic_%`)) %>% 
  dplyr::select(papel, `roic_%`) %>% 
  filter(papel %in% c("ENBR3", "PETR4", "SULA11",
                      "CSMG3", "CMIG4", "ENAT3",
                      "MGLU3", "BBSE3", "BBAS3",
                      "SAPR4", "EQTL3", "CMIN3",
                      "VALE3", "BBDC4", "TAEE11",
                      "B3SA3", "ITSA4", "RANI3",
                      "MULT3"))
```


```{r}
# ML (Margem líquido)
# ML = Lucro líquido / Receitas líquidos
fundamentus2 %>% 
  arrange(desc(`mrg_liq_%`)) %>% 
  dplyr::select(papel, `mrg_liq_%`) %>% 
  filter(papel %in% c("ENBR3", "PETR4", "SULA11",
                      "CSMG3", "CMIG4", "ENAT3",
                      "MGLU3", "BBSE3", "BBAS3",
                      "SAPR4", "EQTL3", "CMIN3",
                      "VALE3", "BBDC4", "TAEE11",
                      "B3SA3", "ITSA4", "RANI3",
                      "MULT3"))
```
```{r}
# MEBIT (Margem EBIT)
# MEBIT = EBIT / Receita líquida
fundamentus2 %>% 
  arrange(desc(`mrg_ebit_%`)) %>% 
  dplyr::select(papel, `mrg_ebit_%`) %>% 
  filter(papel %in% c("ENBR3", "PETR4", "SULA11",
                      "CSMG3", "CMIG4", "ENAT3",
                      "MGLU3", "BBSE3", "BBAS3",
                      "SAPR4", "EQTL3", "CMIN3",
                      "VALE3", "BBDC4", "TAEE11",
                      "B3SA3", "ITSA4", "RANI3",
                      "MULT3"))
```
# Indicadores de mercado

```{r}
# P/L preço sobre lucro (anos para ter de volta o retorno)
# P/L = cotação (R$) / Lucro por ação (LPA)
# LPA = Lucro líquido / Quantidade de ações
# Valor ideal < 15 
fundamentus2 %>% 
  arrange(desc(`p_l`)) %>% 
  dplyr::select(papel, `p_l`) %>% 
  filter(papel %in% c("ENBR3", "PETR4", "SULA11",
                      "CSMG3", "CMIG4", "ENAT3",
                      "MGLU3", "BBSE3", "BBAS3",
                      "SAPR4", "EQTL3", "CMIN3",
                      "VALE3", "BBDC4", "TAEE11",
                      "B3SA3", "ITSA4", "RANI3",
                      "MULT3"))
```
```{r}
# P/VP preço sobre o valor patrimonial
# P/VPA = cotação (R$) / Valor patrimonial da ação (VPA)
# VPA = Patrimonio liquido / Quantidade de ações
# Abaixo de 1 - descontado (Otimo para fundos imobiliarios) 
fundamentus2 %>% 
  arrange(desc(`p_vp`)) %>% 
  dplyr::select(papel, `p_vp`) %>% 
  filter(papel %in% c("ENBR3", "PETR4", "SULA11",
                      "CSMG3", "CMIG4", "ENAT3",
                      "MGLU3", "BBSE3", "BBAS3",
                      "SAPR4", "EQTL3", "CMIN3",
                      "VALE3", "BBDC4", "TAEE11",
                      "B3SA3", "ITSA4", "RANI3",
                      "MULT3"))
```

```{r}
# PSR - Price Sales Ratio
# PSR = cotação (R$) / Receita liquida / qde de ações
# Abaixo de 1 - descontado 
fundamentus2 %>% 
  arrange(desc(`psr`)) %>% 
  dplyr::select(papel, `psr`) %>% 
  filter(papel %in% c("ENBR3", "PETR4", "SULA11",
                      "CSMG3", "CMIG4", "ENAT3",
                      "MGLU3", "BBSE3", "BBAS3",
                      "SAPR4", "EQTL3", "CMIN3",
                      "VALE3", "BBDC4", "TAEE11",
                      "B3SA3", "ITSA4", "RANI3",
                      "MULT3"))
```


```{r}
# Dividend yield - % dividendo pago por ação
# Div yield = Dividendo pago / Cotação da açaão
fundamentus2 %>% 
  arrange(desc(`div_yield_%`)) %>% 
  dplyr::select(papel, `div_yield_%`) %>% 
  filter(papel %in% c("ENBR3", "PETR4", "SULA11",
                      "CSMG3", "CMIG4", "ENAT3",
                      "MGLU3", "BBSE3", "BBAS3",
                      "SAPR4", "EQTL3", "CMIN3",
                      "VALE3", "BBDC4", "TAEE11",
                      "B3SA3", "ITSA4", "RANI3",
                      "MULT3"))
```

```{r}
# EV / EBITDA 
# EV - Enterprise value - Valor total da empresa (acoes + dividas)
# EBITDA- Lucro operacional antes de juros, impostos, amortizacao e depreciacao)
fundamentus2 %>% 
  arrange(desc(`ev_ebitda`)) %>% 
  dplyr::select(papel, `ev_ebitda`) %>% 
  filter(papel %in% c("ENBR3", "PETR4", "SULA11",
                      "CSMG3", "CMIG4", "ENAT3",
                      "MGLU3", "BBSE3", "BBAS3",
                      "SAPR4", "EQTL3", "CMIN3",
                      "VALE3", "BBDC4", "TAEE11",
                      "B3SA3", "ITSA4", "RANI3",
                      "MULT3"))
```




```{r}
proventos_function <- function(papel) {
  
  url <- paste0("https://www.fundamentus.com.br/proventos.php?papel=",papel,"&tipo=2")
  
  #papel will change by each papel code
  
  # Read url
  papel <- read_html(url)
  
  # Extract herbicide resistance data
  papel1 <- papel %>% 
    html_node("table") %>% # selector 
    html_table(fill = TRUE) # get the table

  

  
# Tidy dataset
  papel2 <- papel1 %>% 
    janitor::clean_names() %>% 
    as_tibble() %>% #str_replace_all(., "\\-", "NA")) %>% 
    mutate(data_de_pagamento = if_else(
                                       data_de_pagamento == "-", "", data_de_pagamento)) %>% 
    mutate_if(is_character, ~ str_replace_all(., "\\/", "\\-")) %>% 
    mutate_at("valor",
            ~ as.double(str_replace_all(., ",", "\\."))) %>% 
    rename(data_com = data) %>% 
    mutate(data_com = lubridate::dmy(data_com),
           data_de_pagamento = lubridate::dmy(data_de_pagamento),
           tipo = as_factor(tipo),
           data_com_mes = lubridate::month(data_com, label = TRUE),
           data_com_ano = lubridate::year(data_com),
           data_com_dia = lubridate::day(data_com)) %>% 
    mutate(tipo = str_to_title(tipo),
           tipo = fct_recode(tipo,
                             "Jrs Cap Próprio" = "Jrs Cap Proprio")) %>% 
    mutate(valor_uma_acao = valor / por_quantas_acoes) %>% 
    dplyr::select(data_com, data_com_mes, data_com_dia, valor, valor_uma_acao, everything())
  papel2 
}
```


```{r}
fundamentus2 %>% 
  mutate(proventos = map(papel, proventos_function))
```


```{r}
proventos_function("EMBR3") %>% 
  ggplot(aes(x = data_com, y = valor_uma_acao, color = tipo, group = tipo)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(name = "Valor por 1 ação (R$)") +
  scale_x_date() +
  labs(x = "Data com") +
  theme_test() +
  theme(axis.text.x = element_text(angle = 90))
```




