---
title: "planilha_mira"
author: "Maxwel Coura Oliveira"
date: "5/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```


```{r}
options(scipen = 999)
library(tidyverse)
```


```{r}
status <- read_csv2("statusinvest-busca-avancada.csv")
setores <- read_csv("b3_setores.csv")
```




```{r}
risco <- 16
EPR <- 9.5 # % premio de risco de investir na bolsa
EPR_IPCA <- 15
```


```{r}
status1 <- status %>% 
  mutate(DPA = (DY/100) * PRECO) %>% 
  mutate(valuation_bazin_RS = DPA / 0.06) %>% 
  mutate(`desconto_bazin_%` = ((PRECO - valuation_bazin_RS) / valuation_bazin_RS)*100) %>% 
  mutate(valuation_grahan_RS = (22.5 * LPA * VPA)^0.5) %>% 
  mutate(`desconto_grahan_%` = ((PRECO - valuation_grahan_RS) / 
                                  valuation_grahan_RS)*100) %>% 
  mutate(valuation_gordon_RS = (DPA * (1 + (`CAGR LUCROS 5 ANOS`/100))) / risco) %>% 
  mutate(`desconto_gordon_%` = ((PRECO - valuation_gordon_RS) / 
                                  valuation_gordon_RS)*100) %>%      
  mutate(PAYOUT = DPA / LPA) %>% 
  mutate(cescimento_esperado = (1 - PAYOUT) * ROE) %>% 
  mutate(media_crescimento = (`CAGR LUCROS 5 ANOS` + cescimento_esperado)/2) %>% 
  mutate_if(is.double, ~round(., 2))
```


```{r}
status2 <- status1 %>% 
  left_join(setores, by = "TICKER") %>% 
  dplyr::select(TICKER, EMPRESA, PRECO, `SETOR ECONÔMICO`, SUBSETOR, SEGMENTO, 
                PRECO, valuation_bazin_RS, `desconto_bazin_%`, valuation_grahan_RS, 
                `desconto_grahan_%`, valuation_gordon_RS, `desconto_gordon_%`,
                cescimento_esperado, media_crescimento) %>% 
  arrange(SEGMENTO)
```



```{r}
status2 %>% 
  DT::datatable()
```

