---
title: "valuation"
author: "Maxwel Coura Oliveira"
date: "5/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(rvest)
library(tidyverse)
library(lubridate)
```


```{r}
fundamentus <- read_html("https://www.fundamentus.com.br/resultado.php")
```



```{r}
fundamentus1 <- fundamentus %>% 
    html_node("table") %>% # selector = table
    html_table(fill = TRUE) # get a table
```


```{r}
fundamentus2 <- fundamentus1 %>% 
  janitor::clean_names() %>% 
  mutate(papel = as_factor(papel)) %>% 
  mutate_if(is.character,
            ~ str_replace_all(., "\\.", "")) %>% 
  mutate_if(is_character, ~ str_replace_all(., ",", "\\.")) %>% 
  mutate_at(c("div_yield", "mrg_liq", "roe", "cresc_rec_5a", "mrg_ebit", "roic"), 
            ~ str_remove(., "%")) %>% 
  rename(`div_yield_%` = div_yield,
         `mrg_liq_%` = mrg_liq,
         `roe_%` = roe,
         `cresc_rec_5a_%` = cresc_rec_5a,
         `roic_%` = roic,
         `mrg_ebit_%` = mrg_ebit) %>% 
  mutate_if(is_character, as.double)
```


```{r}
risco <- 16
EPR <- 9.5 # % premio de risco de investir na bolsa
EPR_IPCA <- 15
```


```{r}
fundamentus3 <- fundamentus2 %>% 
  mutate(dpa = (`div_yield_%`/100) * cotacao) %>% 
  mutate(valuation_bazin_RS = dpa / 0.06) %>% 
  mutate(`desconto_bazin_%` = ((cotacao - valuation_bazin_RS) / valuation_bazin_RS)*100) %>% 
  mutate(valuation_grahan_RS = (22.5 * LPA * VPA)^0.5) %>% 
  mutate(`desconto_grahan_%` = ((dpa - valuation_grahan_RS) / 
                                  valuation_grahan_RS)*100) %>% 
  mutate(valuation_gordon_RS = (dpa * (1 + (`CAGR LUCROS 5 ANOS`/100))) / risco) %>% 
  mutate(`desconto_gordon_%` = ((dpa - valuation_gordon_RS) / 
                                  valuation_gordon_RS)*100) %>%      
  mutate(payout = dpa / LPA) %>% 
  mutate(cescimento_esperado = (1 - payout) * `roe_%`) %>% 
  mutate(media_crescimento = (`cresc_rec_5a_%` + cescimento_esperado)/2) %>% 
  mutate_if(is.double, ~round(., 2))
```



